# https://school.programmers.co.kr/learn/courses/30/lessons/59413

# 보호소에서는 몇 시에 입양이 가장 활발하게 일어나는지 알아보려 합니다.
# 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회하는 SQL문을 작성해주세요.
# 이때 결과는 시간대 순으로 정렬해야 합니다.
SET @i = -1;
SELECT H.HOUR, IFNULL(C.COUNT, 0)
FROM (SELECT @i:=@i+1 HOUR FROM ANIMAL_OUTS WHERE @i<23) H
    LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(ANIMAL_ID) COUNT FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME)) C ON H.HOUR=C.HOUR
ORDER BY H.HOUR

SET @i = -1;
SELECT @i:=@i+1 HOUR, (SELECT COUNT(ANIMAL_ID) FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=@i) COUNT
FROM ANIMAL_OUTS
WHERE @i<23
ORDER BY HOUR

SELECT H.HOUR, IFNULL(C.COUNT, 0) COUNT FROM
(SELECT 0 HOUR UNION ALL
 SELECT 1 UNION ALL
 SELECT 2 UNION ALL
 SELECT 3 UNION ALL
 SELECT 4 UNION ALL
 SELECT 5 UNION ALL
 SELECT 6 UNION ALL
 SELECT 7 UNION ALL
 SELECT 8 UNION ALL
 SELECT 9 UNION ALL
 SELECT 10 UNION ALL
 SELECT 11 UNION ALL
 SELECT 12 UNION ALL
 SELECT 13 UNION ALL
 SELECT 14 UNION ALL
 SELECT 15 UNION ALL
 SELECT 16 UNION ALL
 SELECT 17 UNION ALL
 SELECT 18 UNION ALL
 SELECT 19 UNION ALL
 SELECT 20 UNION ALL
 SELECT 21 UNION ALL
 SELECT 22 UNION ALL
 SELECT 23) H
    LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(ANIMAL_ID) COUNT FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME)) C ON H.HOUR=C.HOUR
ORDER BY H.HOUR
