# https://school.programmers.co.kr/learn/courses/30/lessons/151141

# CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서
# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여
# 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요.
# 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.
SELECT H.HISTORY_ID,
       CASE
           WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1>=90 THEN TRUNCATE(C.DAILY_FEE*(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1)*(100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='90일 이상'))/100, 0)
           WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1>=30 THEN TRUNCATE(C.DAILY_FEE*(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1)*(100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='30일 이상'))/100, 0)
           WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1>=7 THEN TRUNCATE(C.DAILY_FEE*(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1)*(100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='7일 이상'))/100, 0)
           ELSE TRUNCATE(C.DAILY_FEE*(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1), 0)
       END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID=C.CAR_ID
WHERE C.CAR_TYPE='트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
